Fix missing nzbget.h includes causing compilation errors
Include nzbget.h before other headers in UrlCoordinator.cpp and
PathsValidator.cpp to ensure functions and types are properly declared
before use.

Without this fix, compilation fails with errors like:
```
/var/tmp/portage/net-nntp/nzbget-26.0/work/nzbget-26.0/daemon/queue/UrlCoordinator.cpp:208:25: error: ‘error’ was not declared in this scope
  208 |                         error("Cancelling hanging url download %s", urlDownloader->GetInfoName());
      |                         ^~~~~
```
```
/var/tmp/portage/net-nntp/nzbget-26.0/work/nzbget-26.0/daemon/util/NString.h:67:17: error: ‘free’ was not declared in this scope
   67 |                 free(m_data);
      |                 ^~~~
```